[web]
  title = Supabase Redwood Quickstart
  port = 8910
  apiProxyPath = /.redwood/functions
  includeEnvironmentVariables = [SUPABASE_URL, SUPABASE_KEY]
[api]
  port = 8911
[browser]
  open = true


